import type { Blocks } from '../../../types/endpoints'

const removeRes: Blocks.Delete.Response = {
    archived: true,
    child_database: { title: 'Updated Database For Testing' },
    created_time: 'some_created_time',
    has_children: false,
    id: 'some_id',
    last_edited_time: 'some_last_edited_time',
    object: 'block',
    type: 'child_database',
}

const retrieveRes: Blocks.Retrieve.Response = {
    archived: false,
    child_page: { title: 'page title' },
    created_time: 'some_created_time',
    has_children: true,
    id: 'some_id',
    last_edited_time: 'some_last_edited_time',
    object: 'block',
    type: 'child_page',
}

const updateRes: Blocks.Update.Response = {
    archived: false,
    created_time: 'some_created_time',
    has_children: true,
    id: 'some_id',
    last_edited_time: 'some_last_edited_time',
    object: 'block',
    paragraph: {
        text: [
            {
                annotations: {
                    bold: false,
                    code: false,
                    color: 'default',
                    italic: false,
                    strikethrough: false,
                    underline: false,
                },
                href: 'some_href',
                mention: { page: { id: 'some_id' }, type: 'page' },
                plain_text: 'page title',
                type: 'mention',
            },
            {
                annotations: {
                    bold: false,
                    code: false,
                    color: 'default',
                    italic: false,
                    strikethrough: false,
                    underline: false,
                },
                href: 'some_href',
                mention: { database: { id: 'some_id' }, type: 'database' },
                plain_text: 'Updated Database For Testing',
                type: 'mention',
            },
            {
                annotations: {
                    bold: false,
                    code: false,
                    color: 'default',
                    italic: false,
                    strikethrough: false,
                    underline: false,
                },
                href: null,
                mention: {
                    date: {
                        end: null,
                        start: '2000-01-01T05:00:00.000+00:00',
                        time_zone: null,
                    },
                    type: 'date',
                },
                plain_text: '2000-01-01T05:00:00.000+00:00 → ',
                type: 'mention',
            },
        ],
    },
    type: 'paragraph',
}

const childrenAppendRes: Blocks.Children.Append.Response = {
    has_more: false,
    next_cursor: null,
    object: 'list',
    results: [
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            paragraph: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'paragraph',
                        text: { content: 'paragraph', link: null },
                        type: 'text',
                    },
                ],
            },
            type: 'paragraph',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            heading_1: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'heading 1',
                        text: { content: 'heading 1', link: null },
                        type: 'text',
                    },
                ],
            },
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'heading_1',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            heading_2: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'heading 2',
                        text: { content: 'heading 2', link: null },
                        type: 'text',
                    },
                ],
            },
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'heading_2',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            heading_3: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'heading 3',
                        text: { content: 'heading 3', link: null },
                        type: 'text',
                    },
                ],
            },
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'heading_3',
        },
        {
            archived: false,
            bulleted_list_item: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'bulleted list item',
                        text: { content: 'bulleted list item', link: null },
                        type: 'text',
                    },
                ],
            },
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'bulleted_list_item',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            numbered_list_item: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'numbered list item',
                        text: { content: 'numbered list item', link: null },
                        type: 'text',
                    },
                ],
            },
            object: 'block',
            type: 'numbered_list_item',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            to_do: {
                checked: true,
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'to do',
                        text: { content: 'to do', link: null },
                        type: 'text',
                    },
                ],
            },
            type: 'to_do',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            toggle: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'toggle',
                        text: { content: 'toggle', link: null },
                        type: 'text',
                    },
                ],
            },
            type: 'toggle',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            embed: {
                caption: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'embed',
                        text: { content: 'embed', link: null },
                        type: 'text',
                    },
                ],
                url: 'some_url',
            },
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'embed',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: false,
            id: 'some_id',
            image: {
                caption: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'image',
                        text: { content: 'image', link: null },
                        type: 'text',
                    },
                ],
                external: { url: 'some_url' },
                type: 'external',
            },
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'image',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'video',
            video: {
                caption: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'video',
                        text: { content: 'video', link: null },
                        type: 'text',
                    },
                ],
                external: { url: 'some_url' },
                type: 'external',
            },
        },
        {
            archived: false,
            created_time: 'some_created_time',
            file: {
                caption: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'file',
                        text: { content: 'file', link: null },
                        type: 'text',
                    },
                ],
                external: { url: 'some_url' },
                type: 'external',
            },
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'file',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            pdf: {
                caption: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'pdf',
                        text: { content: 'pdf', link: null },
                        type: 'text',
                    },
                ],
                external: { url: 'some_url' },
                type: 'external',
            },
            type: 'pdf',
        },
        {
            archived: false,
            bookmark: {
                caption: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'bookmark',
                        text: { content: 'bookmark', link: null },
                        type: 'text',
                    },
                ],
                url: 'some_url',
            },
            created_time: 'some_created_time',
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'bookmark',
        },
        {
            archived: false,
            callout: {
                icon: { emoji: '💡', type: 'emoji' },
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'callout',
                        text: { content: 'callout', link: null },
                        type: 'text',
                    },
                ],
            },
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'callout',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            quote: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'quote',
                        text: { content: 'quote', link: null },
                        type: 'text',
                    },
                ],
            },
            type: 'quote',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            equation: { expression: 'e=mc^2' },
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'equation',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            divider: {},
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'divider',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            table_of_contents: {},
            type: 'table_of_contents',
        },
        {
            archived: false,
            breadcrumb: {},
            created_time: 'some_created_time',
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'breadcrumb',
        },
        {
            archived: false,
            column_list: {},
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            type: 'column_list',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            synced_block: {
                synced_from: { block_id: 'some_block_id', type: 'block_id' },
            },
            type: 'synced_block',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            template: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'template',
                        text: { content: 'template', link: null },
                        type: 'text',
                    },
                ],
            },
            type: 'template',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: false,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            link_to_page: {
                database_id: 'some_database_id',
                type: 'database_id',
            },
            object: 'block',
            type: 'link_to_page',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            table: {
                has_column_header: false,
                has_row_header: false,
                table_width: 2,
            },
            type: 'table',
        },
    ],
}

const childrenRetrieveRes: Blocks.Children.Retrieve.Response = {
    has_more: false,
    next_cursor: null,
    object: 'list',
    results: [
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            paragraph: {
                text: [
                    {
                        annotations: {
                            bold: false,
                            code: false,
                            color: 'default',
                            italic: false,
                            strikethrough: false,
                            underline: false,
                        },
                        href: null,
                        plain_text: 'paragraph',
                        text: { content: 'paragraph', link: null },
                        type: 'text',
                    },
                ],
            },
            type: 'paragraph',
        },
        {
            archived: false,
            created_time: 'some_created_time',
            has_children: true,
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'block',
            synced_block: { synced_from: null },
            type: 'synced_block',
        },
    ],
}
