import type { Databases } from '../../../types/endpoints'

const createRes: Databases.Create.Response = {
    cover: null,
    created_time: 'some_created_time',
    icon: null,
    id: 'some_id',
    last_edited_time: 'some_last_edited_time',
    object: 'database',
    parent: { page_id: 'some_page_id', type: 'page_id' },
    properties: {
        'date (basic)': {
            date: {},
            id: 'some_id',
            name: 'date (basic)',
            type: 'date',
        },
        'number (dollar)': {
            id: 'some_id',
            name: 'number (dollar)',
            number: { format: 'dollar' },
            type: 'number',
        },
        person: { id: 'some_id', name: 'person', people: {}, type: 'people' },
        title: { id: 'some_id', name: 'title', title: {}, type: 'title' },
    },
    title: [
        {
            annotations: {
                bold: false,
                code: false,
                color: 'default',
                italic: false,
                strikethrough: false,
                underline: false,
            },
            href: null,
            plain_text: 'Database For Testing',
            text: { content: 'Database For Testing', link: null },
            type: 'text',
        },
    ],
    url: 'some_url',
}

const queryRes: Databases.Query.Response = {
    has_more: false,
    next_cursor: null,
    object: 'list',
    results: [
        {
            archived: false,
            cover: null,
            created_time: 'some_created_time',
            icon: { emoji: '🧪', type: 'emoji' },
            id: 'some_id',
            last_edited_time: 'some_last_edited_time',
            object: 'page',
            parent: { database_id: 'some_database_id', type: 'database_id' },
            properties: {
                checkbox: { checkbox: true, id: 'some_id', type: 'checkbox' },
                'created by': {
                    created_by: {
                        avatar_url: null,
                        bot: {},
                        id: 'some_id',
                        name: 'Testing',
                        object: 'user',
                        type: 'bot',
                    },
                    id: 'some_id',
                    type: 'created_by',
                },
                'created time': {
                    created_time: 'some_created_time',
                    id: 'some_id',
                    type: 'created_time',
                },
                'date (basic)': {
                    date: {
                        end: null,
                        start: '2000-01-01T05:00:00.000+00:00',
                        time_zone: null,
                    },
                    id: 'some_id',
                    type: 'date',
                },
                'date (duration)': {
                    date: {
                        end: '2010-01-01T05:00:00.000+00:00',
                        start: '2000-01-01T05:00:00.000+00:00',
                        time_zone: null,
                    },
                    id: 'some_id',
                    type: 'date',
                },
                'date (timezone)': {
                    date: {
                        end: null,
                        start: '2000-01-01T05:00:00.000-05:00',
                        time_zone: null,
                    },
                    id: 'some_id',
                    type: 'date',
                },
                'email address': {
                    email: 'hidden_email',
                    id: 'some_id',
                    type: 'email',
                },
                files: {
                    files: [
                        {
                            external: { url: 'some_url' },
                            name: 'Spotify Logo',
                            type: 'external',
                        },
                    ],
                    id: 'some_id',
                    type: 'files',
                },
                formula: {
                    formula: { number: 34.96, type: 'number' },
                    id: 'some_id',
                    type: 'formula',
                },
                'last edited by': {
                    id: 'some_id',
                    last_edited_by: {
                        avatar_url: null,
                        bot: {},
                        id: 'some_id',
                        name: 'Testing',
                        object: 'user',
                        type: 'bot',
                    },
                    type: 'last_edited_by',
                },
                'last edited time': {
                    id: 'some_id',
                    last_edited_time: 'some_last_edited_time',
                    type: 'last_edited_time',
                },
                'local url': { id: 'some_id', type: 'url', url: 'some_url' },
                'mutli select': {
                    id: 'some_id',
                    multi_select: [
                        { color: 'yellow', id: 'some_id', name: 'option 2' },
                        { color: 'pink', id: 'some_id', name: 'option 4' },
                    ],
                    type: 'multi_select',
                },
                'number (dollar)': {
                    id: 'some_id',
                    number: 17.48,
                    type: 'number',
                },
                person: {
                    id: 'some_id',
                    people: [
                        {
                            avatar_url: null,
                            id: 'some_id',
                            name: 'Ben Keys (test account)',
                            object: 'user',
                            person: { email: 'hidden_email' },
                            type: 'person',
                        },
                    ],
                    type: 'people',
                },
                'phone number': {
                    id: 'some_id',
                    phone_number: '(555) 555-5555',
                    type: 'phone_number',
                },
                'relation (self)': {
                    id: 'some_id',
                    relation: [{ id: 'some_id' }],
                    type: 'relation',
                },
                'rich text - equation': {
                    id: 'some_id',
                    rich_text: [
                        {
                            annotations: {
                                bold: false,
                                code: false,
                                color: 'default',
                                italic: false,
                                strikethrough: false,
                                underline: false,
                            },
                            equation: { expression: 'e=mc^2' },
                            href: null,
                            plain_text: 'e=mc^2',
                            type: 'equation',
                        },
                    ],
                    type: 'rich_text',
                },
                'rich text - mentions': {
                    id: 'some_id',
                    rich_text: [
                        {
                            annotations: {
                                bold: false,
                                code: false,
                                color: 'default',
                                italic: false,
                                strikethrough: false,
                                underline: false,
                            },
                            href: null,
                            mention: {
                                date: {
                                    end: null,
                                    start: '2000-01-01T05:00:00.000+00:00',
                                    time_zone: null,
                                },
                                type: 'date',
                            },
                            plain_text: '2000-01-01T05:00:00.000+00:00 → ',
                            type: 'mention',
                        },
                    ],
                    type: 'rich_text',
                },
                'rich text - text': {
                    id: 'some_id',
                    rich_text: [
                        {
                            annotations: {
                                bold: false,
                                code: false,
                                color: 'blue_background',
                                italic: false,
                                strikethrough: false,
                                underline: false,
                            },
                            href: null,
                            plain_text: 'hello ',
                            text: { content: 'hello ', link: null },
                            type: 'text',
                        },
                        {
                            annotations: {
                                bold: false,
                                code: false,
                                color: 'default',
                                italic: false,
                                strikethrough: false,
                                underline: true,
                            },
                            href: null,
                            plain_text: 'world! ',
                            text: { content: 'world! ', link: null },
                            type: 'text',
                        },
                        {
                            annotations: {
                                bold: true,
                                code: false,
                                color: 'default',
                                italic: false,
                                strikethrough: false,
                                underline: false,
                            },
                            href: null,
                            plain_text: 'hello ',
                            text: { content: 'hello ', link: null },
                            type: 'text',
                        },
                        {
                            annotations: {
                                bold: false,
                                code: false,
                                color: 'default',
                                italic: false,
                                strikethrough: false,
                                underline: false,
                            },
                            href: 'some_href',
                            plain_text: 'world! ',
                            text: {
                                content: 'world! ',
                                link: { url: 'some_url' },
                            },
                            type: 'text',
                        },
                        {
                            annotations: {
                                bold: false,
                                code: false,
                                color: 'brown',
                                italic: false,
                                strikethrough: true,
                                underline: false,
                            },
                            href: null,
                            plain_text: 'hello ',
                            text: { content: 'hello ', link: null },
                            type: 'text',
                        },
                        {
                            annotations: {
                                bold: false,
                                code: true,
                                color: 'default',
                                italic: false,
                                strikethrough: false,
                                underline: false,
                            },
                            href: null,
                            plain_text: 'world! ',
                            text: { content: 'world! ', link: null },
                            type: 'text',
                        },
                    ],
                    type: 'rich_text',
                },
                'rollups - array': {
                    id: 'some_id',
                    rollup: {
                        array: [],
                        function: 'show_original',
                        type: 'array',
                    },
                    type: 'rollup',
                },
                'rollups - date': {
                    id: 'some_id',
                    rollup: {
                        date: null,
                        function: 'earliest_date',
                        type: 'date',
                    },
                    type: 'rollup',
                },
                'rollups - number': {
                    id: 'some_id',
                    rollup: {
                        function: 'average',
                        number: null,
                        type: 'number',
                    },
                    type: 'rollup',
                },
                'single select': {
                    id: 'some_id',
                    select: {
                        color: 'purple',
                        id: 'some_id',
                        name: 'option 3',
                    },
                    type: 'select',
                },
                title: {
                    id: 'some_id',
                    title: [
                        {
                            annotations: {
                                bold: false,
                                code: false,
                                color: 'default',
                                italic: false,
                                strikethrough: false,
                                underline: false,
                            },
                            href: null,
                            plain_text: 'page title',
                            text: { content: 'page title', link: null },
                            type: 'text',
                        },
                    ],
                    type: 'title',
                },
            },
            url: 'some_url',
        },
    ],
}

const retrieveRes: Databases.Retrieve.Response = {
    cover: null,
    created_time: 'some_created_time',
    icon: null,
    id: 'some_id',
    last_edited_time: 'some_last_edited_time',
    object: 'database',
    parent: { page_id: 'some_page_id', type: 'page_id' },
    properties: {
        checkbox: {
            checkbox: {},
            id: 'some_id',
            name: 'checkbox',
            type: 'checkbox',
        },
        'created by': {
            created_by: {},
            id: 'some_id',
            name: 'created by',
            type: 'created_by',
        },
        'created time': {
            created_time: {},
            id: 'some_id',
            name: 'created time',
            type: 'created_time',
        },
        'date (basic)': {
            date: {},
            id: 'some_id',
            name: 'date (basic)',
            type: 'date',
        },
        'date (duration)': {
            date: {},
            id: 'some_id',
            name: 'date (duration)',
            type: 'date',
        },
        'date (timezone)': {
            date: {},
            id: 'some_id',
            name: 'date (timezone)',
            type: 'date',
        },
        'email address': {
            email: {},
            id: 'some_id',
            name: 'email address',
            type: 'email',
        },
        files: { files: {}, id: 'some_id', name: 'files', type: 'files' },
        formula: {
            formula: { expression: 'prop("number (dollar)") * 2' },
            id: 'some_id',
            name: 'formula',
            type: 'formula',
        },
        'last edited by': {
            id: 'some_id',
            last_edited_by: {},
            name: 'last edited by',
            type: 'last_edited_by',
        },
        'last edited time': {
            id: 'some_id',
            last_edited_time: {},
            name: 'last edited time',
            type: 'last_edited_time',
        },
        'local url': { id: 'some_id', name: 'local url', type: 'url', url: {} },
        'mutli select': {
            id: 'some_id',
            multi_select: {
                options: [
                    { color: 'blue', id: 'some_id', name: 'option 1' },
                    { color: 'yellow', id: 'some_id', name: 'option 2' },
                    { color: 'purple', id: 'some_id', name: 'option 3' },
                    { color: 'pink', id: 'some_id', name: 'option 4' },
                    { color: 'red', id: 'some_id', name: 'option 5' },
                ],
            },
            name: 'mutli select',
            type: 'multi_select',
        },
        'number (dollar)': {
            id: 'some_id',
            name: 'number (dollar)',
            number: { format: 'dollar' },
            type: 'number',
        },
        person: { id: 'some_id', name: 'person', people: {}, type: 'people' },
        'phone number': {
            id: 'some_id',
            name: 'phone number',
            phone_number: {},
            type: 'phone_number',
        },
        'relation (self)': {
            id: 'some_id',
            name: 'relation (self)',
            relation: {
                database_id: 'some_database_id',
                synced_property_id: 'some_synced_property_id',
                synced_property_name: 'relation (self)',
            },
            type: 'relation',
        },
        'rich text - equation': {
            id: 'some_id',
            name: 'rich text - equation',
            rich_text: {},
            type: 'rich_text',
        },
        'rich text - mentions': {
            id: 'some_id',
            name: 'rich text - mentions',
            rich_text: {},
            type: 'rich_text',
        },
        'rich text - text': {
            id: 'some_id',
            name: 'rich text - text',
            rich_text: {},
            type: 'rich_text',
        },
        'rollups - array': {
            id: 'some_id',
            name: 'rollups - array',
            rollup: {
                function: 'show_original',
                relation_property_id: 'some_relation_property_id',
                relation_property_name: 'relation (self)',
                rollup_property_id: 'some_rollup_property_id',
                rollup_property_name: 'person',
            },
            type: 'rollup',
        },
        'rollups - date': {
            id: 'some_id',
            name: 'rollups - date',
            rollup: {
                function: 'earliest_date',
                relation_property_id: 'some_relation_property_id',
                relation_property_name: 'relation (self)',
                rollup_property_id: 'some_rollup_property_id',
                rollup_property_name: 'date (basic)',
            },
            type: 'rollup',
        },
        'rollups - number': {
            id: 'some_id',
            name: 'rollups - number',
            rollup: {
                function: 'average',
                relation_property_id: 'some_relation_property_id',
                relation_property_name: 'relation (self)',
                rollup_property_id: 'some_rollup_property_id',
                rollup_property_name: 'number (dollar)',
            },
            type: 'rollup',
        },
        'single select': {
            id: 'some_id',
            name: 'single select',
            select: {
                options: [
                    { color: 'blue', id: 'some_id', name: 'option 1' },
                    { color: 'yellow', id: 'some_id', name: 'option 2' },
                    { color: 'purple', id: 'some_id', name: 'option 3' },
                    { color: 'pink', id: 'some_id', name: 'option 4' },
                    { color: 'red', id: 'some_id', name: 'option 5' },
                ],
            },
            type: 'select',
        },
        title: { id: 'some_id', name: 'title', title: {}, type: 'title' },
    },
    title: [
        {
            annotations: {
                bold: false,
                code: false,
                color: 'default',
                italic: false,
                strikethrough: false,
                underline: false,
            },
            href: null,
            plain_text: 'Updated Database For Testing',
            text: { content: 'Updated Database For Testing', link: null },
            type: 'text',
        },
    ],
    url: 'some_url',
}

const updateRes: Databases.Update.Response = {
    cover: null,
    created_time: 'some_created_time',
    icon: null,
    id: 'some_id',
    last_edited_time: 'some_last_edited_time',
    object: 'database',
    parent: { page_id: 'some_page_id', type: 'page_id' },
    properties: {
        checkbox: {
            checkbox: {},
            id: 'some_id',
            name: 'checkbox',
            type: 'checkbox',
        },
        'created by': {
            created_by: {},
            id: 'some_id',
            name: 'created by',
            type: 'created_by',
        },
        'created time': {
            created_time: {},
            id: 'some_id',
            name: 'created time',
            type: 'created_time',
        },
        'date (basic)': {
            date: {},
            id: 'some_id',
            name: 'date (basic)',
            type: 'date',
        },
        'date (duration)': {
            date: {},
            id: 'some_id',
            name: 'date (duration)',
            type: 'date',
        },
        'date (timezone)': {
            date: {},
            id: 'some_id',
            name: 'date (timezone)',
            type: 'date',
        },
        'email address': {
            email: {},
            id: 'some_id',
            name: 'email address',
            type: 'email',
        },
        files: { files: {}, id: 'some_id', name: 'files', type: 'files' },
        formula: {
            formula: { expression: 'prop("number (dollar)") * 2' },
            id: 'some_id',
            name: 'formula',
            type: 'formula',
        },
        'last edited by': {
            id: 'some_id',
            last_edited_by: {},
            name: 'last edited by',
            type: 'last_edited_by',
        },
        'last edited time': {
            id: 'some_id',
            last_edited_time: {},
            name: 'last edited time',
            type: 'last_edited_time',
        },
        'local url': { id: 'some_id', name: 'local url', type: 'url', url: {} },
        'mutli select': {
            id: 'some_id',
            multi_select: {
                options: [
                    { color: 'blue', id: 'some_id', name: 'option 1' },
                    { color: 'yellow', id: 'some_id', name: 'option 2' },
                    { color: 'purple', id: 'some_id', name: 'option 3' },
                    { color: 'pink', id: 'some_id', name: 'option 4' },
                    { color: 'red', id: 'some_id', name: 'option 5' },
                ],
            },
            name: 'mutli select',
            type: 'multi_select',
        },
        'number (dollar)': {
            id: 'some_id',
            name: 'number (dollar)',
            number: { format: 'dollar' },
            type: 'number',
        },
        person: { id: 'some_id', name: 'person', people: {}, type: 'people' },
        'phone number': {
            id: 'some_id',
            name: 'phone number',
            phone_number: {},
            type: 'phone_number',
        },
        'relation (self)': {
            id: 'some_id',
            name: 'relation (self)',
            relation: {
                database_id: 'some_database_id',
                synced_property_id: 'some_synced_property_id',
                synced_property_name: 'relation (self)',
            },
            type: 'relation',
        },
        'rich text - equation': {
            id: 'some_id',
            name: 'rich text - equation',
            rich_text: {},
            type: 'rich_text',
        },
        'rich text - mentions': {
            id: 'some_id',
            name: 'rich text - mentions',
            rich_text: {},
            type: 'rich_text',
        },
        'rich text - text': {
            id: 'some_id',
            name: 'rich text - text',
            rich_text: {},
            type: 'rich_text',
        },
        'rollups - array': {
            id: 'some_id',
            name: 'rollups - array',
            rollup: {
                function: 'show_original',
                relation_property_id: 'some_relation_property_id',
                relation_property_name: 'relation (self)',
                rollup_property_id: 'some_rollup_property_id',
                rollup_property_name: 'person',
            },
            type: 'rollup',
        },
        'rollups - date': {
            id: 'some_id',
            name: 'rollups - date',
            rollup: {
                function: 'earliest_date',
                relation_property_id: 'some_relation_property_id',
                relation_property_name: 'relation (self)',
                rollup_property_id: 'some_rollup_property_id',
                rollup_property_name: 'date (basic)',
            },
            type: 'rollup',
        },
        'rollups - number': {
            id: 'some_id',
            name: 'rollups - number',
            rollup: {
                function: 'average',
                relation_property_id: 'some_relation_property_id',
                relation_property_name: 'relation (self)',
                rollup_property_id: 'some_rollup_property_id',
                rollup_property_name: 'number (dollar)',
            },
            type: 'rollup',
        },
        'single select': {
            id: 'some_id',
            name: 'single select',
            select: {
                options: [
                    { color: 'blue', id: 'some_id', name: 'option 1' },
                    { color: 'yellow', id: 'some_id', name: 'option 2' },
                    { color: 'purple', id: 'some_id', name: 'option 3' },
                    { color: 'pink', id: 'some_id', name: 'option 4' },
                    { color: 'red', id: 'some_id', name: 'option 5' },
                ],
            },
            type: 'select',
        },
        title: { id: 'some_id', name: 'title', title: {}, type: 'title' },
    },
    title: [
        {
            annotations: {
                bold: false,
                code: false,
                color: 'default',
                italic: false,
                strikethrough: false,
                underline: false,
            },
            href: null,
            plain_text: 'Updated Database For Testing',
            text: { content: 'Updated Database For Testing', link: null },
            type: 'text',
        },
    ],
    url: 'some_url',
}
