import { Page } from '..'

const page: Page = {
    object: 'page',
    id: '003bd3fd-67e0-4c56-bca4-48bc7575f49e',
    created_time: '2021-12-31T14:31:00.000Z',
    last_edited_time: '2021-12-31T18:16:00.000Z',
    cover: null,
    icon: null,
    parent: {
        type: 'database_id',
        database_id: '1d05903f-7b76-465a-b4f0-feb577927e8f',
    },
    archived: false,
    properties: {
        'phone number': {
            id: '%3B%7Cvs',
            type: 'phone_number',
            phone_number: '(555) 555-5555',
        },
        'rich text - equation': {
            id: '%3DNd%40',
            type: 'rich_text',
            rich_text: [
                {
                    type: 'equation',
                    equation: { expression: 'e = mc^2' },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: 'e = mc^2',
                    href: null,
                },
            ],
        },
        'last edited by': {
            id: '%3D%5D%40t',
            type: 'last_edited_by',
            last_edited_by: {
                object: 'user',
                id: 'db49262a-227e-4b55-afff-075c453a279c',
                name: 'Ben Keys',
                avatar_url: null,
                type: 'person',
                person: { email: 'bakeys@bsu.edu' },
            },
        },
        'number (dollar)': { id: 'C%40uA', type: 'number', number: 17.48 },
        'mutli select': {
            id: 'CN%7C%7B',
            type: 'multi_select',
            multi_select: [
                {
                    id: '6f2455cc-d2f6-4770-a730-169cb3842b0d',
                    name: 'item 1',
                    color: 'green',
                },
                {
                    id: '05d0c3ff-b321-4277-a3bc-962d7330caad',
                    name: 'item 2',
                    color: 'blue',
                },
                {
                    id: '669bde9f-ec79-4ef0-adaa-fb3aa1140d2d',
                    name: 'item 3',
                    color: 'purple',
                },
                {
                    id: 'a5d2a896-ffa6-4066-8f3f-eb952259053b',
                    name: 'item 4',
                    color: 'pink',
                },
                {
                    id: '7158656f-8cfd-409f-80e6-b7057a02facd',
                    name: 'item 5',
                    color: 'red',
                },
            ],
        },
        checkbox: { id: 'DK%7DE', type: 'checkbox', checkbox: false },
        formula: {
            id: 'E%3AyU',
            type: 'formula',
            formula: { type: 'number', number: 105 },
        },
        'created time': {
            id: 'F%5B%3CV',
            type: 'created_time',
            created_time: '2021-12-31T14:31:00.000Z',
        },
        'rollups - number': {
            id: 'HkTE',
            type: 'rollup',
            rollup: { type: 'number', number: 17.48, function: 'average' },
        },
        'rollups - array': {
            id: 'JmID',
            type: 'rollup',
            rollup: {
                type: 'array',
                array: [
                    {
                        type: 'multi_select',
                        multi_select: [
                            {
                                id: '6f2455cc-d2f6-4770-a730-169cb3842b0d',
                                name: 'item 1',
                                color: 'green',
                            },
                            {
                                id: '05d0c3ff-b321-4277-a3bc-962d7330caad',
                                name: 'item 2',
                                color: 'blue',
                            },
                            {
                                id: '669bde9f-ec79-4ef0-adaa-fb3aa1140d2d',
                                name: 'item 3',
                                color: 'purple',
                            },
                            {
                                id: 'a5d2a896-ffa6-4066-8f3f-eb952259053b',
                                name: 'item 4',
                                color: 'pink',
                            },
                            {
                                id: '7158656f-8cfd-409f-80e6-b7057a02facd',
                                name: 'item 5',
                                color: 'red',
                            },
                        ],
                    },
                ],
                function: 'show_original',
            },
        },
        'local url': {
            id: 'KD%3F%5B',
            type: 'url',
            url: 'http://localhost:8000',
        },
        'single select': {
            id: 'MurH',
            type: 'select',
            select: {
                id: '2cbb5387-8447-43a8-ad2e-7656c8020133',
                name: 'item 3',
                color: 'brown',
            },
        },
        'date (basic)': {
            id: 'PpW%3D',
            type: 'date',
            date: { start: '2000-01-01', end: null, time_zone: null },
        },
        'relation (self)': {
            id: 'RcgO',
            type: 'relation',
            relation: [{ id: '003bd3fd-67e0-4c56-bca4-48bc7575f49e' }],
        },
        'rich text - mentions': {
            id: 'VQ%3FF',
            type: 'rich_text',
            rich_text: [
                {
                    type: 'mention',
                    mention: {
                        type: 'user',
                        user: {
                            object: 'user',
                            id: 'db49262a-227e-4b55-afff-075c453a279c',
                            name: 'Ben Keys',
                            avatar_url: null,
                            type: 'person',
                            person: { email: 'bakeys@bsu.edu' },
                        },
                    },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: '@Ben Keys',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: ' ', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: ' ',
                    href: null,
                },
            ],
        },
        'last edited time': {
            id: 'ZNYt',
            type: 'last_edited_time',
            last_edited_time: '2021-12-31T18:16:00.000Z',
        },
        files: {
            id: '%5Be%5D%7C',
            type: 'files',
            files: [
                {
                    name: 'package.json',
                    type: 'file',
                    file: {
                        url: 'https://s3.us-west-2.amazonaws.com/secure.notion-static.com/c200e37e-994c-4849-8fd4-7bea7206bce2/package.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20211231%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20211231T213146Z&X-Amz-Expires=3600&X-Amz-Signature=153ab9fe6a6b909c9618f5947605612cd23de43df89686283a37322e28e9527c&X-Amz-SignedHeaders=host&x-id=GetObject',
                        expiry_time: '2021-12-31T22:31:46.615Z',
                    },
                },
                {
                    name: 'https://storage.googleapis.com/pr-newsroom-wp/1/2018/11/Spotify_Logo_RGB_Green.png',
                    type: 'external',
                    external: {
                        url: 'https://storage.googleapis.com/pr-newsroom-wp/1/2018/11/Spotify_Logo_RGB_Green.png',
                    },
                },
            ],
        },
        'date (duration)': {
            id: '%5EkRO',
            type: 'date',
            date: { start: '2000-01-01', end: '2000-12-31', time_zone: null },
        },
        'rollups - date': {
            id: 'cka%40',
            type: 'rollup',
            rollup: {
                type: 'date',
                date: { start: '2000-01-01', end: null, time_zone: null },
                function: 'earliest_date',
            },
        },
        'rich text - text': {
            id: 'fRmw',
            type: 'rich_text',
            rich_text: [
                {
                    type: 'text',
                    text: { content: 'hello', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'blue_background',
                    },
                    plain_text: 'hello',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: ' ', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: ' ',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: 'world!', link: null },
                    annotations: {
                        bold: false,
                        italic: true,
                        strikethrough: false,
                        underline: true,
                        code: false,
                        color: 'default',
                    },
                    plain_text: 'world!',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: ' ', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: ' ',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: 'hello', link: null },
                    annotations: {
                        bold: true,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: 'hello',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: ' ', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: ' ',
                    href: null,
                },
                {
                    type: 'text',
                    text: {
                        content: 'world!',
                        link: { url: 'http://localhost:8080' },
                    },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: 'world!',
                    href: 'http://localhost:8080',
                },
                {
                    type: 'text',
                    text: { content: ' ', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: ' ',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: 'hello', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: true,
                        underline: false,
                        code: false,
                        color: 'brown',
                    },
                    plain_text: 'hello',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: ' ', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: ' ',
                    href: null,
                },
                {
                    type: 'text',
                    text: { content: 'world!d', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: true,
                        color: 'default',
                    },
                    plain_text: 'world!d',
                    href: null,
                },
            ],
        },
        person: {
            id: 'gUtO',
            type: 'people',
            people: [
                {
                    object: 'user',
                    id: 'db49262a-227e-4b55-afff-075c453a279c',
                    name: 'Ben Keys',
                    avatar_url: null,
                    type: 'person',
                    person: { email: 'bakeys@bsu.edu' },
                },
            ],
        },
        'date (timezone)': {
            id: 'nZAZ',
            type: 'date',
            date: {
                start: '2000-01-01T00:00:00.000-05:00',
                end: null,
                time_zone: null,
            },
        },
        'email address': {
            id: 'oHTz',
            type: 'email',
            email: 'yourusername@example.com',
        },
        'created by': {
            id: 'uADj',
            type: 'created_by',
            created_by: {
                object: 'user',
                id: 'db49262a-227e-4b55-afff-075c453a279c',
                name: 'Ben Keys',
                avatar_url: null,
                type: 'person',
                person: { email: 'bakeys@bsu.edu' },
            },
        },
        name: {
            id: 'title',
            type: 'title',
            title: [
                {
                    type: 'text',
                    text: { content: 'basic title', link: null },
                    annotations: {
                        bold: false,
                        italic: false,
                        strikethrough: false,
                        underline: false,
                        code: false,
                        color: 'default',
                    },
                    plain_text: 'basic title',
                    href: null,
                },
            ],
        },
    },
    url: 'https://www.notion.so/basic-title-003bd3fd67e04c56bca448bc7575f49e',
}
